# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dona/D4/dftd4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dona/D4/dftd4/_build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dona/D4/cmake-3.14.1-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dona/D4/dftd4/_build/CMakeFiles /home/dona/D4/dftd4/_build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dona/D4/dftd4/_build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dftd4-lib

# Build rule for target.
dftd4-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dftd4-lib
.PHONY : dftd4-lib

# fast build rule for target.
dftd4-lib/fast:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/build
.PHONY : dftd4-lib/fast

#=============================================================================
# Target rules for targets named mctc-lib-lib

# Build rule for target.
mctc-lib-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mctc-lib-lib
.PHONY : mctc-lib-lib

# fast build rule for target.
mctc-lib-lib/fast:
	$(MAKE) -f _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/build.make _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/build
.PHONY : mctc-lib-lib/fast

#=============================================================================
# Target rules for targets named mctc-convert

# Build rule for target.
mctc-convert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mctc-convert
.PHONY : mctc-convert

# fast build rule for target.
mctc-convert/fast:
	$(MAKE) -f _deps/mctc-lib-build/app/CMakeFiles/mctc-convert.dir/build.make _deps/mctc-lib-build/app/CMakeFiles/mctc-convert.dir/build
.PHONY : mctc-convert/fast

#=============================================================================
# Target rules for targets named mctc-lib-tester

# Build rule for target.
mctc-lib-tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mctc-lib-tester
.PHONY : mctc-lib-tester

# fast build rule for target.
mctc-lib-tester/fast:
	$(MAKE) -f _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/build.make _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/build
.PHONY : mctc-lib-tester/fast

#=============================================================================
# Target rules for targets named mstore-lib

# Build rule for target.
mstore-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mstore-lib
.PHONY : mstore-lib

# fast build rule for target.
mstore-lib/fast:
	$(MAKE) -f _deps/mstore-build/CMakeFiles/mstore-lib.dir/build.make _deps/mstore-build/CMakeFiles/mstore-lib.dir/build
.PHONY : mstore-lib/fast

#=============================================================================
# Target rules for targets named mstore-fortranize

# Build rule for target.
mstore-fortranize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mstore-fortranize
.PHONY : mstore-fortranize

# fast build rule for target.
mstore-fortranize/fast:
	$(MAKE) -f _deps/mstore-build/app/fortranize/CMakeFiles/mstore-fortranize.dir/build.make _deps/mstore-build/app/fortranize/CMakeFiles/mstore-fortranize.dir/build
.PHONY : mstore-fortranize/fast

#=============================================================================
# Target rules for targets named mstore-info

# Build rule for target.
mstore-info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mstore-info
.PHONY : mstore-info

# fast build rule for target.
mstore-info/fast:
	$(MAKE) -f _deps/mstore-build/app/info/CMakeFiles/mstore-info.dir/build.make _deps/mstore-build/app/info/CMakeFiles/mstore-info.dir/build
.PHONY : mstore-info/fast

#=============================================================================
# Target rules for targets named multicharge-lib

# Build rule for target.
multicharge-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multicharge-lib
.PHONY : multicharge-lib

# fast build rule for target.
multicharge-lib/fast:
	$(MAKE) -f _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/build.make _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/build
.PHONY : multicharge-lib/fast

#=============================================================================
# Target rules for targets named multicharge-exe

# Build rule for target.
multicharge-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multicharge-exe
.PHONY : multicharge-exe

# fast build rule for target.
multicharge-exe/fast:
	$(MAKE) -f _deps/multicharge-build/app/CMakeFiles/multicharge-exe.dir/build.make _deps/multicharge-build/app/CMakeFiles/multicharge-exe.dir/build
.PHONY : multicharge-exe/fast

#=============================================================================
# Target rules for targets named multicharge-tester

# Build rule for target.
multicharge-tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multicharge-tester
.PHONY : multicharge-tester

# fast build rule for target.
multicharge-tester/fast:
	$(MAKE) -f _deps/multicharge-build/test/CMakeFiles/multicharge-tester.dir/build.make _deps/multicharge-build/test/CMakeFiles/multicharge-tester.dir/build
.PHONY : multicharge-tester/fast

#=============================================================================
# Target rules for targets named dftd4-exe

# Build rule for target.
dftd4-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dftd4-exe
.PHONY : dftd4-exe

# fast build rule for target.
dftd4-exe/fast:
	$(MAKE) -f app/CMakeFiles/dftd4-exe.dir/build.make app/CMakeFiles/dftd4-exe.dir/build
.PHONY : dftd4-exe/fast

#=============================================================================
# Target rules for targets named dftd4-api-tester

# Build rule for target.
dftd4-api-tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dftd4-api-tester
.PHONY : dftd4-api-tester

# fast build rule for target.
dftd4-api-tester/fast:
	$(MAKE) -f test/api/CMakeFiles/dftd4-api-tester.dir/build.make test/api/CMakeFiles/dftd4-api-tester.dir/build
.PHONY : dftd4-api-tester/fast

#=============================================================================
# Target rules for targets named dftd4-tester

# Build rule for target.
dftd4-tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dftd4-tester
.PHONY : dftd4-tester

# fast build rule for target.
dftd4-tester/fast:
	$(MAKE) -f test/unit/CMakeFiles/dftd4-tester.dir/build.make test/unit/CMakeFiles/dftd4-tester.dir/build
.PHONY : dftd4-tester/fast

src/dftd4.o: src/dftd4.f90.o

.PHONY : src/dftd4.o

# target to build an object file
src/dftd4.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4.f90.o
.PHONY : src/dftd4.f90.o

src/dftd4.i: src/dftd4.f90.i

.PHONY : src/dftd4.i

# target to preprocess a source file
src/dftd4.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4.f90.i
.PHONY : src/dftd4.f90.i

src/dftd4.s: src/dftd4.f90.s

.PHONY : src/dftd4.s

# target to generate assembly for a file
src/dftd4.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4.f90.s
.PHONY : src/dftd4.f90.s

src/dftd4/api.o: src/dftd4/api.f90.o

.PHONY : src/dftd4/api.o

# target to build an object file
src/dftd4/api.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/api.f90.o
.PHONY : src/dftd4/api.f90.o

src/dftd4/api.i: src/dftd4/api.f90.i

.PHONY : src/dftd4/api.i

# target to preprocess a source file
src/dftd4/api.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/api.f90.i
.PHONY : src/dftd4/api.f90.i

src/dftd4/api.s: src/dftd4/api.f90.s

.PHONY : src/dftd4/api.s

# target to generate assembly for a file
src/dftd4/api.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/api.f90.s
.PHONY : src/dftd4/api.f90.s

src/dftd4/blas.o: src/dftd4/blas.F90.o

.PHONY : src/dftd4/blas.o

# target to build an object file
src/dftd4/blas.F90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/blas.F90.o
.PHONY : src/dftd4/blas.F90.o

src/dftd4/blas.i: src/dftd4/blas.F90.i

.PHONY : src/dftd4/blas.i

# target to preprocess a source file
src/dftd4/blas.F90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/blas.F90.i
.PHONY : src/dftd4/blas.F90.i

src/dftd4/blas.s: src/dftd4/blas.F90.s

.PHONY : src/dftd4/blas.s

# target to generate assembly for a file
src/dftd4/blas.F90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/blas.F90.s
.PHONY : src/dftd4/blas.F90.s

src/dftd4/charge.o: src/dftd4/charge.f90.o

.PHONY : src/dftd4/charge.o

# target to build an object file
src/dftd4/charge.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/charge.f90.o
.PHONY : src/dftd4/charge.f90.o

src/dftd4/charge.i: src/dftd4/charge.f90.i

.PHONY : src/dftd4/charge.i

# target to preprocess a source file
src/dftd4/charge.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/charge.f90.i
.PHONY : src/dftd4/charge.f90.i

src/dftd4/charge.s: src/dftd4/charge.f90.s

.PHONY : src/dftd4/charge.s

# target to generate assembly for a file
src/dftd4/charge.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/charge.f90.s
.PHONY : src/dftd4/charge.f90.s

src/dftd4/compat.o: src/dftd4/compat.f90.o

.PHONY : src/dftd4/compat.o

# target to build an object file
src/dftd4/compat.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/compat.f90.o
.PHONY : src/dftd4/compat.f90.o

src/dftd4/compat.i: src/dftd4/compat.f90.i

.PHONY : src/dftd4/compat.i

# target to preprocess a source file
src/dftd4/compat.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/compat.f90.i
.PHONY : src/dftd4/compat.f90.i

src/dftd4/compat.s: src/dftd4/compat.f90.s

.PHONY : src/dftd4/compat.s

# target to generate assembly for a file
src/dftd4/compat.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/compat.f90.s
.PHONY : src/dftd4/compat.f90.s

src/dftd4/cutoff.o: src/dftd4/cutoff.f90.o

.PHONY : src/dftd4/cutoff.o

# target to build an object file
src/dftd4/cutoff.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/cutoff.f90.o
.PHONY : src/dftd4/cutoff.f90.o

src/dftd4/cutoff.i: src/dftd4/cutoff.f90.i

.PHONY : src/dftd4/cutoff.i

# target to preprocess a source file
src/dftd4/cutoff.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/cutoff.f90.i
.PHONY : src/dftd4/cutoff.f90.i

src/dftd4/cutoff.s: src/dftd4/cutoff.f90.s

.PHONY : src/dftd4/cutoff.s

# target to generate assembly for a file
src/dftd4/cutoff.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/cutoff.f90.s
.PHONY : src/dftd4/cutoff.f90.s

src/dftd4/damping.o: src/dftd4/damping.f90.o

.PHONY : src/dftd4/damping.o

# target to build an object file
src/dftd4/damping.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping.f90.o
.PHONY : src/dftd4/damping.f90.o

src/dftd4/damping.i: src/dftd4/damping.f90.i

.PHONY : src/dftd4/damping.i

# target to preprocess a source file
src/dftd4/damping.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping.f90.i
.PHONY : src/dftd4/damping.f90.i

src/dftd4/damping.s: src/dftd4/damping.f90.s

.PHONY : src/dftd4/damping.s

# target to generate assembly for a file
src/dftd4/damping.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping.f90.s
.PHONY : src/dftd4/damping.f90.s

src/dftd4/damping/atm.o: src/dftd4/damping/atm.f90.o

.PHONY : src/dftd4/damping/atm.o

# target to build an object file
src/dftd4/damping/atm.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/atm.f90.o
.PHONY : src/dftd4/damping/atm.f90.o

src/dftd4/damping/atm.i: src/dftd4/damping/atm.f90.i

.PHONY : src/dftd4/damping/atm.i

# target to preprocess a source file
src/dftd4/damping/atm.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/atm.f90.i
.PHONY : src/dftd4/damping/atm.f90.i

src/dftd4/damping/atm.s: src/dftd4/damping/atm.f90.s

.PHONY : src/dftd4/damping/atm.s

# target to generate assembly for a file
src/dftd4/damping/atm.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/atm.f90.s
.PHONY : src/dftd4/damping/atm.f90.s

src/dftd4/damping/rational.o: src/dftd4/damping/rational.f90.o

.PHONY : src/dftd4/damping/rational.o

# target to build an object file
src/dftd4/damping/rational.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/rational.f90.o
.PHONY : src/dftd4/damping/rational.f90.o

src/dftd4/damping/rational.i: src/dftd4/damping/rational.f90.i

.PHONY : src/dftd4/damping/rational.i

# target to preprocess a source file
src/dftd4/damping/rational.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/rational.f90.i
.PHONY : src/dftd4/damping/rational.f90.i

src/dftd4/damping/rational.s: src/dftd4/damping/rational.f90.s

.PHONY : src/dftd4/damping/rational.s

# target to generate assembly for a file
src/dftd4/damping/rational.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/damping/rational.f90.s
.PHONY : src/dftd4/damping/rational.f90.s

src/dftd4/data.o: src/dftd4/data.f90.o

.PHONY : src/dftd4/data.o

# target to build an object file
src/dftd4/data.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data.f90.o
.PHONY : src/dftd4/data.f90.o

src/dftd4/data.i: src/dftd4/data.f90.i

.PHONY : src/dftd4/data.i

# target to preprocess a source file
src/dftd4/data.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data.f90.i
.PHONY : src/dftd4/data.f90.i

src/dftd4/data.s: src/dftd4/data.f90.s

.PHONY : src/dftd4/data.s

# target to generate assembly for a file
src/dftd4/data.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data.f90.s
.PHONY : src/dftd4/data.f90.s

src/dftd4/data/covrad.o: src/dftd4/data/covrad.f90.o

.PHONY : src/dftd4/data/covrad.o

# target to build an object file
src/dftd4/data/covrad.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/covrad.f90.o
.PHONY : src/dftd4/data/covrad.f90.o

src/dftd4/data/covrad.i: src/dftd4/data/covrad.f90.i

.PHONY : src/dftd4/data/covrad.i

# target to preprocess a source file
src/dftd4/data/covrad.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/covrad.f90.i
.PHONY : src/dftd4/data/covrad.f90.i

src/dftd4/data/covrad.s: src/dftd4/data/covrad.f90.s

.PHONY : src/dftd4/data/covrad.s

# target to generate assembly for a file
src/dftd4/data/covrad.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/covrad.f90.s
.PHONY : src/dftd4/data/covrad.f90.s

src/dftd4/data/en.o: src/dftd4/data/en.f90.o

.PHONY : src/dftd4/data/en.o

# target to build an object file
src/dftd4/data/en.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/en.f90.o
.PHONY : src/dftd4/data/en.f90.o

src/dftd4/data/en.i: src/dftd4/data/en.f90.i

.PHONY : src/dftd4/data/en.i

# target to preprocess a source file
src/dftd4/data/en.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/en.f90.i
.PHONY : src/dftd4/data/en.f90.i

src/dftd4/data/en.s: src/dftd4/data/en.f90.s

.PHONY : src/dftd4/data/en.s

# target to generate assembly for a file
src/dftd4/data/en.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/en.f90.s
.PHONY : src/dftd4/data/en.f90.s

src/dftd4/data/hardness.o: src/dftd4/data/hardness.f90.o

.PHONY : src/dftd4/data/hardness.o

# target to build an object file
src/dftd4/data/hardness.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/hardness.f90.o
.PHONY : src/dftd4/data/hardness.f90.o

src/dftd4/data/hardness.i: src/dftd4/data/hardness.f90.i

.PHONY : src/dftd4/data/hardness.i

# target to preprocess a source file
src/dftd4/data/hardness.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/hardness.f90.i
.PHONY : src/dftd4/data/hardness.f90.i

src/dftd4/data/hardness.s: src/dftd4/data/hardness.f90.s

.PHONY : src/dftd4/data/hardness.s

# target to generate assembly for a file
src/dftd4/data/hardness.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/hardness.f90.s
.PHONY : src/dftd4/data/hardness.f90.s

src/dftd4/data/r4r2.o: src/dftd4/data/r4r2.f90.o

.PHONY : src/dftd4/data/r4r2.o

# target to build an object file
src/dftd4/data/r4r2.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/r4r2.f90.o
.PHONY : src/dftd4/data/r4r2.f90.o

src/dftd4/data/r4r2.i: src/dftd4/data/r4r2.f90.i

.PHONY : src/dftd4/data/r4r2.i

# target to preprocess a source file
src/dftd4/data/r4r2.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/r4r2.f90.i
.PHONY : src/dftd4/data/r4r2.f90.i

src/dftd4/data/r4r2.s: src/dftd4/data/r4r2.f90.s

.PHONY : src/dftd4/data/r4r2.s

# target to generate assembly for a file
src/dftd4/data/r4r2.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/r4r2.f90.s
.PHONY : src/dftd4/data/r4r2.f90.s

src/dftd4/data/zeff.o: src/dftd4/data/zeff.f90.o

.PHONY : src/dftd4/data/zeff.o

# target to build an object file
src/dftd4/data/zeff.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/zeff.f90.o
.PHONY : src/dftd4/data/zeff.f90.o

src/dftd4/data/zeff.i: src/dftd4/data/zeff.f90.i

.PHONY : src/dftd4/data/zeff.i

# target to preprocess a source file
src/dftd4/data/zeff.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/zeff.f90.i
.PHONY : src/dftd4/data/zeff.f90.i

src/dftd4/data/zeff.s: src/dftd4/data/zeff.f90.s

.PHONY : src/dftd4/data/zeff.s

# target to generate assembly for a file
src/dftd4/data/zeff.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/data/zeff.f90.s
.PHONY : src/dftd4/data/zeff.f90.s

src/dftd4/disp.o: src/dftd4/disp.f90.o

.PHONY : src/dftd4/disp.o

# target to build an object file
src/dftd4/disp.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/disp.f90.o
.PHONY : src/dftd4/disp.f90.o

src/dftd4/disp.i: src/dftd4/disp.f90.i

.PHONY : src/dftd4/disp.i

# target to preprocess a source file
src/dftd4/disp.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/disp.f90.i
.PHONY : src/dftd4/disp.f90.i

src/dftd4/disp.s: src/dftd4/disp.f90.s

.PHONY : src/dftd4/disp.s

# target to generate assembly for a file
src/dftd4/disp.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/disp.f90.s
.PHONY : src/dftd4/disp.f90.s

src/dftd4/model.o: src/dftd4/model.f90.o

.PHONY : src/dftd4/model.o

# target to build an object file
src/dftd4/model.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/model.f90.o
.PHONY : src/dftd4/model.f90.o

src/dftd4/model.i: src/dftd4/model.f90.i

.PHONY : src/dftd4/model.i

# target to preprocess a source file
src/dftd4/model.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/model.f90.i
.PHONY : src/dftd4/model.f90.i

src/dftd4/model.s: src/dftd4/model.f90.s

.PHONY : src/dftd4/model.s

# target to generate assembly for a file
src/dftd4/model.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/model.f90.s
.PHONY : src/dftd4/model.f90.s

src/dftd4/ncoord.o: src/dftd4/ncoord.f90.o

.PHONY : src/dftd4/ncoord.o

# target to build an object file
src/dftd4/ncoord.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/ncoord.f90.o
.PHONY : src/dftd4/ncoord.f90.o

src/dftd4/ncoord.i: src/dftd4/ncoord.f90.i

.PHONY : src/dftd4/ncoord.i

# target to preprocess a source file
src/dftd4/ncoord.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/ncoord.f90.i
.PHONY : src/dftd4/ncoord.f90.i

src/dftd4/ncoord.s: src/dftd4/ncoord.f90.s

.PHONY : src/dftd4/ncoord.s

# target to generate assembly for a file
src/dftd4/ncoord.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/ncoord.f90.s
.PHONY : src/dftd4/ncoord.f90.s

src/dftd4/numdiff.o: src/dftd4/numdiff.f90.o

.PHONY : src/dftd4/numdiff.o

# target to build an object file
src/dftd4/numdiff.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/numdiff.f90.o
.PHONY : src/dftd4/numdiff.f90.o

src/dftd4/numdiff.i: src/dftd4/numdiff.f90.i

.PHONY : src/dftd4/numdiff.i

# target to preprocess a source file
src/dftd4/numdiff.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/numdiff.f90.i
.PHONY : src/dftd4/numdiff.f90.i

src/dftd4/numdiff.s: src/dftd4/numdiff.f90.s

.PHONY : src/dftd4/numdiff.s

# target to generate assembly for a file
src/dftd4/numdiff.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/numdiff.f90.s
.PHONY : src/dftd4/numdiff.f90.s

src/dftd4/output.o: src/dftd4/output.f90.o

.PHONY : src/dftd4/output.o

# target to build an object file
src/dftd4/output.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/output.f90.o
.PHONY : src/dftd4/output.f90.o

src/dftd4/output.i: src/dftd4/output.f90.i

.PHONY : src/dftd4/output.i

# target to preprocess a source file
src/dftd4/output.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/output.f90.i
.PHONY : src/dftd4/output.f90.i

src/dftd4/output.s: src/dftd4/output.f90.s

.PHONY : src/dftd4/output.s

# target to generate assembly for a file
src/dftd4/output.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/output.f90.s
.PHONY : src/dftd4/output.f90.s

src/dftd4/param.o: src/dftd4/param.f90.o

.PHONY : src/dftd4/param.o

# target to build an object file
src/dftd4/param.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/param.f90.o
.PHONY : src/dftd4/param.f90.o

src/dftd4/param.i: src/dftd4/param.f90.i

.PHONY : src/dftd4/param.i

# target to preprocess a source file
src/dftd4/param.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/param.f90.i
.PHONY : src/dftd4/param.f90.i

src/dftd4/param.s: src/dftd4/param.f90.s

.PHONY : src/dftd4/param.s

# target to generate assembly for a file
src/dftd4/param.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/param.f90.s
.PHONY : src/dftd4/param.f90.s

src/dftd4/reference.o: src/dftd4/reference.f90.o

.PHONY : src/dftd4/reference.o

# target to build an object file
src/dftd4/reference.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/reference.f90.o
.PHONY : src/dftd4/reference.f90.o

src/dftd4/reference.i: src/dftd4/reference.f90.i

.PHONY : src/dftd4/reference.i

# target to preprocess a source file
src/dftd4/reference.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/reference.f90.i
.PHONY : src/dftd4/reference.f90.i

src/dftd4/reference.s: src/dftd4/reference.f90.s

.PHONY : src/dftd4/reference.s

# target to generate assembly for a file
src/dftd4/reference.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/reference.f90.s
.PHONY : src/dftd4/reference.f90.s

src/dftd4/utils.o: src/dftd4/utils.f90.o

.PHONY : src/dftd4/utils.o

# target to build an object file
src/dftd4/utils.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/utils.f90.o
.PHONY : src/dftd4/utils.f90.o

src/dftd4/utils.i: src/dftd4/utils.f90.i

.PHONY : src/dftd4/utils.i

# target to preprocess a source file
src/dftd4/utils.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/utils.f90.i
.PHONY : src/dftd4/utils.f90.i

src/dftd4/utils.s: src/dftd4/utils.f90.s

.PHONY : src/dftd4/utils.s

# target to generate assembly for a file
src/dftd4/utils.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/utils.f90.s
.PHONY : src/dftd4/utils.f90.s

src/dftd4/version.o: src/dftd4/version.f90.o

.PHONY : src/dftd4/version.o

# target to build an object file
src/dftd4/version.f90.o:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/version.f90.o
.PHONY : src/dftd4/version.f90.o

src/dftd4/version.i: src/dftd4/version.f90.i

.PHONY : src/dftd4/version.i

# target to preprocess a source file
src/dftd4/version.f90.i:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/version.f90.i
.PHONY : src/dftd4/version.f90.i

src/dftd4/version.s: src/dftd4/version.f90.s

.PHONY : src/dftd4/version.s

# target to generate assembly for a file
src/dftd4/version.f90.s:
	$(MAKE) -f CMakeFiles/dftd4-lib.dir/build.make CMakeFiles/dftd4-lib.dir/src/dftd4/version.f90.s
.PHONY : src/dftd4/version.f90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... dftd4-lib"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mctc-lib-lib"
	@echo "... mctc-convert"
	@echo "... mctc-lib-tester"
	@echo "... mstore-lib"
	@echo "... mstore-fortranize"
	@echo "... mstore-info"
	@echo "... multicharge-lib"
	@echo "... multicharge-exe"
	@echo "... multicharge-tester"
	@echo "... dftd4-exe"
	@echo "... dftd4-api-tester"
	@echo "... dftd4-tester"
	@echo "... src/dftd4.o"
	@echo "... src/dftd4.i"
	@echo "... src/dftd4.s"
	@echo "... src/dftd4/api.o"
	@echo "... src/dftd4/api.i"
	@echo "... src/dftd4/api.s"
	@echo "... src/dftd4/blas.o"
	@echo "... src/dftd4/blas.i"
	@echo "... src/dftd4/blas.s"
	@echo "... src/dftd4/charge.o"
	@echo "... src/dftd4/charge.i"
	@echo "... src/dftd4/charge.s"
	@echo "... src/dftd4/compat.o"
	@echo "... src/dftd4/compat.i"
	@echo "... src/dftd4/compat.s"
	@echo "... src/dftd4/cutoff.o"
	@echo "... src/dftd4/cutoff.i"
	@echo "... src/dftd4/cutoff.s"
	@echo "... src/dftd4/damping.o"
	@echo "... src/dftd4/damping.i"
	@echo "... src/dftd4/damping.s"
	@echo "... src/dftd4/damping/atm.o"
	@echo "... src/dftd4/damping/atm.i"
	@echo "... src/dftd4/damping/atm.s"
	@echo "... src/dftd4/damping/rational.o"
	@echo "... src/dftd4/damping/rational.i"
	@echo "... src/dftd4/damping/rational.s"
	@echo "... src/dftd4/data.o"
	@echo "... src/dftd4/data.i"
	@echo "... src/dftd4/data.s"
	@echo "... src/dftd4/data/covrad.o"
	@echo "... src/dftd4/data/covrad.i"
	@echo "... src/dftd4/data/covrad.s"
	@echo "... src/dftd4/data/en.o"
	@echo "... src/dftd4/data/en.i"
	@echo "... src/dftd4/data/en.s"
	@echo "... src/dftd4/data/hardness.o"
	@echo "... src/dftd4/data/hardness.i"
	@echo "... src/dftd4/data/hardness.s"
	@echo "... src/dftd4/data/r4r2.o"
	@echo "... src/dftd4/data/r4r2.i"
	@echo "... src/dftd4/data/r4r2.s"
	@echo "... src/dftd4/data/zeff.o"
	@echo "... src/dftd4/data/zeff.i"
	@echo "... src/dftd4/data/zeff.s"
	@echo "... src/dftd4/disp.o"
	@echo "... src/dftd4/disp.i"
	@echo "... src/dftd4/disp.s"
	@echo "... src/dftd4/model.o"
	@echo "... src/dftd4/model.i"
	@echo "... src/dftd4/model.s"
	@echo "... src/dftd4/ncoord.o"
	@echo "... src/dftd4/ncoord.i"
	@echo "... src/dftd4/ncoord.s"
	@echo "... src/dftd4/numdiff.o"
	@echo "... src/dftd4/numdiff.i"
	@echo "... src/dftd4/numdiff.s"
	@echo "... src/dftd4/output.o"
	@echo "... src/dftd4/output.i"
	@echo "... src/dftd4/output.s"
	@echo "... src/dftd4/param.o"
	@echo "... src/dftd4/param.i"
	@echo "... src/dftd4/param.s"
	@echo "... src/dftd4/reference.o"
	@echo "... src/dftd4/reference.i"
	@echo "... src/dftd4/reference.s"
	@echo "... src/dftd4/utils.o"
	@echo "... src/dftd4/utils.i"
	@echo "... src/dftd4/utils.s"
	@echo "... src/dftd4/version.o"
	@echo "... src/dftd4/version.i"
	@echo "... src/dftd4/version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

